name = "DeFiYield Docs"
license = "MIT"
licenselink = ""
description = "The Techdoc is a Hugo Theme for technical documentation."
homepage = "https://github.com/Anastasiya737/hugo-theme-techdoc.git"
repo = "https://github.com/Anastasiya737/hugo-theme-techdoc.git"
tags = ["Documentation", "Docs", "Responsive", "Google analytics", "Table Of Contents"]
features = ["documentation", "menu"]
min_version = "0.60.0"

[author]
  name = ""
  homepage = ""
